
sudo: false

language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

before_install:
    - wget http://apache.claz.org/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
    - tar zxvf apache-maven-3.3.9-bin.tar.gz
    - chmod +x apache-maven-3.3.9/bin/mvn
    - export M2_HOME=$PWD/apache-maven-3.3.9
    - export PATH=$PWD/apache-maven-3.3.9/bin:${PATH}
    - hash -r
    
before_script:
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$PWD/apache-maven-3.3.9/bin:${PATH}
  - hash -r
  
script: mvn --show-version --errors --batch-mode -Prun-its clean verify -Dittest.debug=false -Dinvoker.streamLogs=true

cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
#notifications:
#    email:
#        - hboutemy@apache.org
